
server:
  port: 8000

spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    config:
      name: common,mysql  # file name
      profile: real        # file profile

    # localhost:8000/oauth/password 로 요청하면 http://localhost:8081/oauth/password 가 마운트 된다
    gateway:
      default-filters:  # 모든 라우터에 적용되는 필터 지정
        - name: GlobalFilter
          args:
            preLogger: true
            postLogger: true
      routes:
        - id: oauth2
          #uri: http://localhost:8081
          uri: lb://OAUTH2
          predicates:
            - Path=/oauth/**
          filters:
            - LoginFilter
        - id: product
          #uri: http://localhost:8081
          uri: lb://PRODUCT
          predicates:
            - Path=/product/**


oauth2:
  url: http://localhost:8081
