
server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: gateway
  # localhost:8000/user/check 로 요청하면 http://localhost:8081/user/check 가 마운트 된다
  cloud:
    gateway:
      default-filters:  # 모든 라우터에 적용되는 필터 지정
        - name: GlobalFilter
          args:
            preLogger: true
            postLogger: true
      routes:
        - id: user
          #uri: http://localhost:8081
          uri: lb://SERVICE-USER # Eureka Application Name
          predicates:
            - Path=/user/**
          filters:
            - AddRequestHeader=reqKey, reqVal # default filter
            - AddResponseHeader=resKey, resVal  # default filter
            - CustomFilter # custom filter

