server:
  port: 8082

spring:
  application:
    name: product
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    config:
      name: common,mysql,circuitBreaker
      profile: real

management:
  endpoints:
    web:
      exposure:
        include: health, refresh, beans