
server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AkkeSun/CommonRepository # 설정파일 git 링크
          default-label: master # branch
